# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_kracken95"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = " command line parsing using Fortran 95 (LICENSE:PD)"
categories = ["command line argument parsing"]
keywords = ["fortran", "command line", "arguments"]
homepage = "https://github.com/urbanjost/M_kracken95.git"

[build]
#auto-executables = true
#auto-examples = false
#auto-tests = false
module-naming = true          # Use default naming convention
###########################################################################
[[test]]
name="test1"
source-dir="test/test1"
main="kracken_test-1.f90"
###########################################################################
[[test]]
name="test2"
source-dir="test/test2"
main="kracken_test-2.f90"
###########################################################################
[[test]]
name="test3"
source-dir="test/test3"
main="kracken_test-3.f90"
###########################################################################
